# Generated by Django 3.1.2 on 2021-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('skills', models.CharField(max_length=300)),
                ('image1', models.ImageField(default='', upload_to='userprof/images')),
                ('image2', models.ImageField(default='', upload_to='userprof/images')),
            ],
        ),
    ]
